<?php
    return [
        "Home" => "घर",
        "Services" => "सेवाहरु",
        "Contact" => "सम्पर्क",
        "Gallery" => "प्रदर्शन भवन",
        "Login" => "लग - इन",
        "Get the best" => "सबै भन्दा राम्रो प्राप्त गर",
        "Medical Consultation, Medicine Order, Medical Visit" => "चिकित्सा परामर्श, चिकित्सा अर्डर, चिकित्सा भ्रमण",
        "and many more..." => "र अरु धेरै...",
        "\"Nature Image #2Nature Image #3" => "\"प्रकृति छवि # 2Naily छवि # 3",
        "Serving Patients" => "बिरामीहरूको सेवा गर्दै",
        "in India, Nepal and Bangladesh" => "भारत, नेपाल र बंगलादेशमा",
        "Trusted VISA and Medical Visit Services" => "विश्वसनीय भिसा र चिकित्सा भ्रमण सेवाहरू",

        "Book Now" => "केछू पुस्तक",
    "Medicines Order and" => "औषधि अर्डर र",
    "Fastest Medicine delivery" => "सब भन्दा छिटो औषधि डेलिभरी",
    "and many more..." => "र अरु धेरै...",
    "Order Now" => "आदेश अब",
    "Patient served" => "बिरामीले सेवा दियो",
    "Doctors tied" => "डाक्टरहरू बाँधिएका थिए",
    "Hospitals tied" => "अस्पतालहरु बाँधे",
    "Medical visits for patients" => "बिरामीहरूको लागि मेडिकल भ्रमणहरू",
    "Our Services" => "हाम्रो सेवाहरू",
    "Medical Consultation" => "चिकित्सा परामर्श",
    "Medicine order" => "चिकित्सा अर्डर",
    "lab test" => "प्रयोगशाला परीक्षण",
    "Visa & Passports for medical visits:" => "भिसा र पासपोर्ट मेडिकल भ्रमणको लागि:",
    "Travel Support for medical purposes:" => "चिकित्सा उद्देश्यका लागि यात्रा समर्थन:",
    "Meet Our Experts" => "हाम्रो विज्ञहरूलाई भेट्नुहोस्",

    "In today's society common people are not aware about their health-related information. Even though the current government has given them various health related facilities, the common people cannot get all those facilities properly, because they do not know the details about how and where to get those facilities. InstaDoctor PVT. LTD." => "आजको समाजमा साधारण मानिसहरूलाई उनीहरूको स्वास्थ्य सम्बन्धी परिचयको बारेमा सचेत छैन। यद्यपि चालू सरकारले उनीहरूलाई विभिन्न स्वास्थ्य सम्बन्धी सुविधा दिएको छ, साधारण मानिसहरूले ठीकसँग सबै सुविधाहरू लिन सक्दैनन्, किनभने ती सुविधाहरू कसरी र ती सुविधाहरू कसरी प्राप्त गर्ने भन्ने बारे जानकारी जान्दैनन्। InstaDoctor PVT. LTD.",
    "Learn More" => "थप जान्नुहोस्",
    "A day in our lives" => "हाम्रो जीवनमा एक दिन",
    "Our Special Events" => "हाम्रो विशेष घटनाहरू",
    "Problems trying to resolve the conflict between the two major realms of Classical physics: Newtonian mechanics Problems trying to resolve the conflict between the two major realms of Classical physics: Newtonian mechanics" => "शास्त्रीय फिजिक्सको दुई मुख्य क्षेत्रहरू बीचको द्वन्द्वलाई हल गर्ने कोशिसमा आएका समस्याहरू: न्यूटनियन यान्त्रिकी समस्याहरू शास्त्रीय भौतिकीको दुई मुख्य क्षेत्रहरू बीचको द्वन्द्वलाई हल गर्ने कोशिस गर्दै: न्यूटनियन यान्त्रिकी",
    "Learn More" => "थप जान्नुहोस्",
    "Check out more Events" => "अझै घटनाहरू हेर्नुहोस्",
    "We at work" => "हामी काममा छौं",
    "Our Videos" => "हाम्रो भिडियोहरू",
    "Problems trying to resolve the conflict between the two major realms of Classical physics: Newtonian mechanics Problems trying to resolve the conflict between the two major realms of Classical physics: Newtonian mechanics" => "शास्त्रीय फिजिक्सको दुई मुख्य क्षेत्रहरू बीचको द्वन्द्वलाई हल गर्ने कोशिसमा आएका समस्याहरू: न्यूटनियन यान्त्रिकी समस्याहरू शास्त्रीय भौतिकीको दुई मुख्य क्षेत्रहरू बीचको द्वन्द्वलाई हल गर्ने कोशिस गर्दै: न्यूटनियन यान्त्रिकी",
    "Testimonials" => "प्रशंसापत्रहरू",

    "Our Happy Customers" => "हाम्रो खुशी ग्राहकहरु",
"Problems trying to resolve the conflict between the two major realms of Classical physics: Newtonian mechanics" => "शास्त्रीय भौतिकीको दुई मुख्य क्षेत्रहरू बीचको द्वन्द्व समाधान गर्न समस्याहरू: न्यूटनियन यान्त्रिकी",
"Any Queries" => "कुनै प्रश्न",
"Contact Us" => "हामीलाई सम्पर्क गर्नुहोस्",
"Do you have any queries, suggestions, or requests? InstaDoctor is a chain of patient care facilities. To contact us, please fill out the form below." => "के तपाईंसँग कुनै प्रश्नहरू, सुझावहरू, वा अनुरोधहरू छन्? InstaDoctor एक रोगी देखभाल सुविधाको श्रृंखला हो। हामीसँग सम्पर्क गर्नका लागि कृपया तलको फारम भर्नुहोस्।",
"Contact Information" => "सम्पर्क जानकारी",
"Your Name" => "तिम्रो नाम",
"Your Email" => "तिम्रो इमेल",
"Head Office Address:" => "हेड अफिस ठेगाना:",
"Hospital Road, Janaushadhi Building, 1st Floor, P.S : Madarihat, P.O : Madarihat, Dist: -Alipurduar, PIN: 735220" => "अस्पताल रोड, जननौषधि भवन, १ औं तल, पी.एस: मदरिहट, पी.ओ: मदरिहट, जिल्ला: -अलिपुरद्वार, पिन: ७३५२२०",
"Phone Number:" => "फोन नम्बर:",
"Whatsapp:" => "Whatsapp:",
"Email:" => "इमेल:",
"send" => "पठाउनु",
"Menu" => "व्यंजन सुची",

"Doctors with us" => "हाम्रो संग डाक्टरहरू",
"Hospitals with us" => "हाम्रो संग अस्पतालहरू",
"Terms and Conditions" => "नियम र सर्तहरू",
"Return and Refund Policy" => "फिर्ता र रिफन्ड नीति",
"Shipping Policy" => "शिपिंग नीति",
"Privacy policy" => "गोपनीयता नीति",
"Download our Android App" => "हाम्रो एन्ड्रोइड अनुप्रयोग डाउनलोड गर्नुहोस्",
"Get In Touch" => "संपर्कमा रहनुहोस्",
"Kolkata Office: Prince Anwar shah road, Tollygaunge, Kolkata" => "कोलकाता कार्यालय: प्रिन्स अनवर शाह रोड, टोलिगांज, कोलकाता",
"Nepal Office: Near Purano Bus Park, Bagbazar, Kathmandu, 44600, Nepal" => "नेपाल कार्यालय: पुरानो बस पार्क बगबाजार, काठमाण्डौं, ४४६००, नेपाल",

        'Home' => 'घर',
        'Contact' =>"संपर्क नंबर",
        'whatsapp'=>"Whatsapp",
        'Email'=>"ईमेल",
        'bannerTitle1'=>"सर्वश्रेष्ठ चिकित्सा परामर्श प्राप्त करें दवाई का ऑर्डर और आपकी मेडिकल विज़िट पर मदद",
        'About' => "हमारे बारे में",
        'AboutDescription'=>"हमारी सेवाएं मरीजों की मदद करती हैं जहां दूरी एक महत्वपूर्ण कारक है। हम अंतर को पाटते हैं और उन्हें सर्वोत्तम चिकित्सा सुविधाओं के संपर्क में लाते हैं। इसलिए हमारी सेवाएं दूर के स्थानों से आने वाले मरीजों को एलोपैथिक, होम्योपैथिक और आयुर्वेदिक उपचार के लिए बेहतर निदान और सहायता के लिए जानकारी प्रदान करने जैसी सुविधाओं के साथ मदद कर सकती हैं। हमारी विशिष्ट सुविधाएं मरीजों को हमारे विशेषज्ञ डॉक्टरों के साथ ऑनलाइन और ऑफलाइन दोनों परामर्श प्राप्त करने, दवा ऑर्डर करने, नैदानिक ​​परीक्षणों का अनुरोध करने, और वीजा या पासपोर्ट से संबंधित मामलों में सहायता प्राप्त करने, भारत के अंदर सभी टिकट, हवाई अड्डे से सेवाओं को लेने और छोड़ने में सक्षम बनाती हैं। ट्रेन स्टेशन और बस स्टॉप आवास, चिकित्सा गाइड और बहुत कुछ।",
        'Services'=>"हमारी सेवाएँ",
        'Medical-Consultation'=>"चिकित्सा परामर्श",
        'MedicalDescription'=>"क्या आप भरोसेमंद डॉक्टरों से परामर्श करना चाहते हैं और सस्ती कीमत पर चिकित्सा सुविधाएं प्राप्त करना चाहते हैं? हमारे पास सबसे अच्छे डॉक्टर पंजीकृत हैं जो न केवल ऑनलाइन परामर्श प्रदान करते हैं बल्कि ऑफ़लाइन भी देखे जा सकते हैं। अधिक जानकारी के लिए हमें नीचे दिए गए नंबर पर कॉल करें।",
        
        'Medical-order'=>"चिकित्सा आदेश",

        'medicalOrder-description'=>"क्या आप कुछ दवाएं मंगवाना चाहते हैं और चाहते हैं कि उन्हें भारत के बाहर उचित कीमत पर कुछ ही समय में वितरित किया जाए? हमारे पास डिलीवरी की एक अद्भुत श्रृंखला है जो यह सुनिश्चित करती है कि आपकी दवाएं आप तक समय पर पहुंचे। दवा मंगवाने के लिए हमें नीचे दिए गए नंबर पर कॉल करें।",

        'labTest'=>"लैब टेस्ट",

        'labTest-description'=>"हमारे इंस्टाडॉक्टर पंजीकृत प्रयोगशालाओं के साथ अपना लैब टेस्ट बुक करें। अपने सभी लैब परीक्षण उचित दर पर करवाएं और परेशानी मुक्त नमूना संग्रह और रिपोर्ट वितरण प्राप्त करें। टेस्ट बुक करने के लिए हमें नीचे दिए गए नंबर पर कॉल करें।",

        'Visa'=>"चिकित्सा यात्राओं के लिए वीजा और पासपोर्ट",

        'Visa-Descreiption'=>"इंस्टाडॉक्टर में हमारी टीम आपको त्वरित चिकित्सा वीज़ा प्राप्त करने के लिए अपना वीज़ा आवेदन तैयार करने में मदद करती है। हम चिकित्सा उद्देश्यों के लिए पासपोर्ट और सीमा पार यात्रा में भी मदद करते हैं। अपनी चिकित्सा यात्राओं पर सहायता प्राप्त करने के लिए हमें नीचे दिए गए नंबर पर कॉल करें।",

        'Travel'=>"चिकित्सा प्रयोजनों के लिए यात्रा सहायता",

        'Travel-description'=>"हम बस, ट्रेन और हवाईजहाज से सभी प्रकार की यात्रा सहायता प्रदान करते हैं। अपने रहने और खाने के बारे में चिंता न करें क्योंकि हम आपकी चिकित्सा यात्राओं के दौरान भी इसका प्रबंधन करते हैं। यदि आवश्यक हो तो हम आपकी सहायता के लिए 24*7 एक चिकित्सा परिचर के साथ टैग करते हैं।",

        'consult' => "सल्लाहकारहरू"
    ];
